services:
  golang:
    container_name: bapsi-management-system-be
    image: golang:1.22.4
    environment:
      - TZ=Asia/Bangkok
    working_dir: /app
    volumes:
      - ./be-bms:/app
    ports:
      - "8000:8000"
    command: "go run ."
    networks:
      mynetwork:
        ipv4_address: 172.41.0.5

  node:
    container_name: bapsi-management-system
    image: node:latest
    working_dir: /var/www
    volumes:
      - ./fe-bms:/var/www
    ports:
      - "3000:3000"
    environment:
      - TZ=Asia/Bangkok
    networks: 
      mynetwork:
        ipv4_address: 172.41.0.3
    command: bash -c "npm install && npm install -g serve && serve -s dist"

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token eyJhIjoiZWIxNDFjYzExNzc3NGNhZjI2ZjgyNjAwYWYxOGI0YjIiLCJ0IjoiMjlkZDUzMDktYTM3Yi00YTBkLTllNzAtNmUzZDg1YTg5MDkyIiwicyI6Ik1EQTBZVFl6T1RndE16QTBPQzAwTjJRNExXRTBNelF0T0RjeU1HSTBNelE0TmpjMSJ9
    networks:
      mynetwork:
        ipv4_address: 172.41.0.2

networks:
  mynetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.41.0.0/16

# volumes:
#   mysql_data:
  
  
  
  # mysql_db:
  #   image: mysql:latest
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=faizal
  #     - MYSQL_DATABASE=bapsi_management_system
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   networks:
  #     mynetwork:
  #       ipv4_address: 172.40.0.4
