build:
	npm run build

serve:
	yarn serve

# ========================================

list:
	git stash list

0:
	git stash pop 0

1:
	git stash pop 1

2:
	git stash pop 2

3:
	git stash pop 3

4:
	git stash pop 4

5:
	git stash pop 5

6:
	git stash pop 6

7:
	git stash pop 7

8:
	git stash pop 8

9:
	git stash pop 9

10:
	git stash pop 10

11:
	git stash pop 11